[package]
name = "cli"
version = "0.1.0"
edition = "2024"

[dependencies]
trace-rpc = { path = "../trace-rpc" }
trace-ir  = { path = "../trace-ir" }
anyhow = "1"
clap = { version = "4", features = ["derive"] }
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
